spring: 
  datasource:
    url: jdbc:mysql://localhost:3306/test?useSSL=false&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
# mybatis-plus config
mybatis-plus: 
  type-aliases-package: com.yicj.mybatis2.entity
  mapper-locations: classpath*:/com/yicj/mybatis2/xml/**Mapper.xml
  global-config:
    db-config:
      table-underline: true #驼峰下划线转换
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
# logging
logging:
  level:
    root: info
    com.yicj.mybatis2: debug
  pattern:
    console: '%p%m%n'